# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'iAerialRobo'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: News
    link: /
  - name: About
    link: /about
  - name: People
    link: /people
  - name: Publications
    link: /publications
  - name: Codes and Datasets
    link: /codes_datasets
  - name: Awards
    link: /awards
  - name: Featured Projects
    submenu:
      - name: Vision-based Control
        link: /projects/vision_based_control
      - name: Reinforcement Learning
        link: /projects/reinforcementlearning
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/iAerialRobo
      - name: Email
        icon: envelope-square
        link: mailto:aehannwoei@usm.my
      - name: Youtube
        icon: youtube
        link: https://youtube.com/@iAerialRobo?si=0mRvsQe0ObzL7mcR
    
