# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'iAerialRobo'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: Featured Projects
    submenu:
      - name: Vision-based Control
        link: /projects/vision_based_control
      - name: Reinforcement Learning
        link: /projects/reinforcementlearning
  - name: Posts
    link: /
  - name: Team
    link: /team
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/iAerialRobo
      - name: LinkedIn
        icon: linkedin-square
        link: http://www.linkedin.com/in/hannwoei
      - name: Youtube
        icon: youtube
        link: https://www.youtube.com/channel/UC-9ygXsRO1gNiIDVMeGonzg
    
